# Generated by Django 5.2.7 on 2025-10-26 10:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='Unique invoice reference number', max_length=50, unique=True)),
                ('customer_name', models.CharField(help_text="Customer's full name", max_length=200)),
                ('customer_email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text="Customer's phone number", max_length=20, null=True)),
                ('customer_address', models.TextField(blank=True, help_text="Customer's address", null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', help_text='Invoice status', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Invoice creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('created_by', models.ForeignKey(help_text='User who created this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Item description', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='Item quantity (must be at least 1)')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Calculated line total (quantity × unit_price)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Item creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('invoice', models.ForeignKey(help_text='Related invoice', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['reference_number'], name='invoices_in_referen_fa2c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='invoices_in_created_67cbdc_idx'),
        ),
    ]
