# Generated by Django 5.2.7 on 2025-10-26 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Sale', 'Sale'), ('Payment', 'Payment')], help_text='Type of transaction: Sale or Payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Transaction timestamp')),
                ('description', models.TextField(blank=True, help_text='Transaction description', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(help_text='Related invoice', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'), models.Index(fields=['-transaction_date'], name='transaction_transac_681486_idx')],
            },
        ),
    ]
